//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bioquimica.Entidades
{
    using System;
    
    public partial class Facturacion
    {
        public string PacienteNombre { get; set; }
        public System.DateTime FechaAtencion { get; set; }
        public string Prepaga { get; set; }
        public int Codigo { get; set; }
        public Nullable<decimal> Subtotal { get; set; }
        public int OrdenId { get; set; }
    }
}
