//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bioquimica.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orden
    {
        public Orden()
        {
            this.PracticasOrdenes = new HashSet<PracticasOrdenes>();
        }
    
        public int OrdenId { get; set; }
        public int PrepagaId { get; set; }
        public int NroOrden { get; set; }
        public string PacienteNombre { get; set; }
        public System.DateTime FechaAtencion { get; set; }
        public Nullable<int> PacienteDNI { get; set; }
        public Nullable<System.DateTime> PacienteFechaNacimiento { get; set; }
        public bool DiscriminaIVA { get; set; }
    
        public virtual Prepaga Prepagas { get; set; }
        public virtual ICollection<PracticasOrdenes> PracticasOrdenes { get; set; }
    }
}
