//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bioquimica.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profesional
    {
        public int ProfesionalId { get; set; }
        public string Apellido { get; set; }
        public string Nombres { get; set; }
        public string Domicilio { get; set; }
        public string Telefono { get; set; }
        public string CUIT { get; set; }
        public int DNI { get; set; }
        public string MP { get; set; }
        public string MN { get; set; }
        public string Provincia { get; set; }
    }
}
